# Generated by Django 3.0.7 on 2020-12-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('ArP', 'Arunachal Pradesh'), ('G', 'Goa'), ('Kn', 'Karnataka'), ('MR', 'Maharashtra'), ('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('UP', 'Uttar Pradesh')], max_length=100),
        ),
    ]
